AllCops:
  Exclude:
    - '.git/**/*'
    - 'vendor/**/*'
    - 'infra/lambdas/*/vendor/**/*'
    - 'terraform/**/*'
    - 'db/schema.rb'
# Layout
Layout/LineLength:
  Max: 100

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# Lint
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantBegin:
  Enabled: false
