default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: delivery_tracking_development

test:
  <<: *default
  database: delivery_tracking_test

production:
  <<: *default
